CREATE TABLE users (
    user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) UNIQUE NOT NULL,
    hashed_password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    role VARCHAR(255) NOT NULL
);

CREATE TABLE todolist (
    task_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT references users (user_id) not null,
    task_title VARCHAR(100) NOT NULL,
    task_description VARCHAR(255),
    priority VARCHAR(10) NOT null,
    completed BOOLEAN DEFAULT false,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
